language: python
before_install:
  - pip install coverage
  - pip install flake8
  - pip install coveralls
script:
  - coverage run -m unittest discover tests
  - flake8 .
after_success:
  - coveralls --service=github
